import os
from dotenv import load_dotenv

load_dotenv()


class LLMClient:
    def __init__(self):
        self.provider = os.getenv("LLM_PROVIDER", "stub")
        self.api_key = os.getenv("ANTHROPIC_API_KEY", "")
        self.stub_mode = self.provider == "stub" or not self.api_key

    def generate(self, prompt: str, max_tokens: int = 4096) -> str:
        if self.stub_mode:
            return self._generate_stub(prompt)

        if self.provider == "claude":
            return self._generate_claude(prompt, max_tokens)

        raise ValueError(f"Unsupported LLM provider: {self.provider}")

    def _generate_stub(self, prompt: str) -> str:
        return (
            f"[STUB MODE] Placeholder response for:\n\n"
            f"{prompt[:100]}...\n\n"
            f"In production, this would be generated by the LLM API."
        )

    def _generate_claude(self, prompt: str, max_tokens: int) -> str:
        try:
            import anthropic

            client = anthropic.Anthropic(api_key=self.api_key)
            message = client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=max_tokens,
                system="You are a professional business consultant writing detailed feasibility reports for Indian businesses.",
                messages=[{"role": "user", "content": prompt}],
            )
            return message.content[0].text

        except ImportError:
            raise ImportError("Anthropic library not installed. Run: pip install anthropic")
        except Exception as e:
            raise Exception(f"Claude API error: {str(e)}")


# Global instance
llm_client = LLMClient()
