import os
import time
import random
from dotenv import load_dotenv
from app.config import Config

load_dotenv()


class LLMClient:
    def __init__(self):
        self.provider = os.getenv("LLM_PROVIDER", "stub")
        self.api_key = os.getenv("ANTHROPIC_API_KEY", "")
        self.stub_mode = self.provider == "stub" or not self.api_key

    def generate(self, prompt: str, max_tokens: int = 4096, mode: str = "plain") -> str:
        if self.stub_mode:
            return self._generate_stub(prompt)

        if self.provider == "claude":
            if mode == "web" and Config.ENABLE_CLAUDE_WEB_SEARCH:
                return self._generate_claude_web(prompt, max_tokens)
            return self._generate_claude_plain(prompt, max_tokens)

        raise ValueError(f"Unsupported LLM provider: {self.provider}")

    def _generate_stub(self, prompt: str) -> str:
        return (
            f"[STUB MODE] Placeholder response for:\n\n"
            f"{prompt[:100]}...\n\n"
            f"In production, this would be generated by the LLM API."
        )

    def _generate_claude_plain(self, prompt: str, max_tokens: int) -> str:
        try:
            import anthropic

            client = anthropic.Anthropic(api_key=self.api_key)
            message = self._claude_messages_create_with_retry(
                client,
                model="claude-sonnet-4-6",
                max_tokens=max_tokens,
                system=(
                    "You are a professional business consultant writing detailed feasibility "
                    "reports for Indian businesses. Use clear structure, practical assumptions, "
                    "and concise business language."
                ),
                messages=[{"role": "user", "content": prompt}],
            )
            return message.content[0].text

        except ImportError:
            raise ImportError("Anthropic library not installed. Run: pip install anthropic")
        except Exception as e:
            raise Exception(f"Claude API error: {str(e)}")

    def _generate_claude_web(self, prompt: str, max_tokens: int) -> str:
        try:
            import anthropic

            client = anthropic.Anthropic(api_key=self.api_key)

            web_search_tool = {
                "type": "web_search_20250305",
                "name": "web_search",
            }

            system = (
                "You are a professional business consultant writing detailed feasibility reports "
                "for Indian businesses. Use web search to look up current market data, regulatory "
                "requirements, industry statistics, equipment costs, and any other facts needed to "
                "produce an accurate and up-to-date report. Always ground your output in real, "
                "searchable information."
            )

            # 1) Single initial call with tools enabled.
            initial = self._claude_messages_create_with_retry(
                client,
                model="claude-sonnet-4-6",
                max_tokens=max_tokens,
                system=system,
                tools=[web_search_tool],
                messages=[{"role": "user", "content": prompt}],
            )

            initial_text = [block.text for block in initial.content if hasattr(block, "text")]
            if initial.stop_reason != "tool_use":
                return "\n".join(initial_text)

            # 2) At most one follow-up call using minimal context.
            #    No iterative conversation accumulation to avoid exploding input tokens.
            tool_results = []
            for block in initial.content:
                if getattr(block, "type", None) == "tool_use":
                    tool_results.append(
                        {
                            "type": "tool_result",
                            "tool_use_id": block.id,
                            "content": block.input.get("query", ""),
                        }
                    )

            if not tool_results:
                return "\n".join(initial_text)

            followup = self._claude_messages_create_with_retry(
                client,
                model="claude-sonnet-4-6",
                max_tokens=max_tokens,
                system=system,
                tools=[web_search_tool],
                messages=[
                    {"role": "user", "content": prompt},
                    {"role": "assistant", "content": initial.content},
                    {"role": "user", "content": tool_results},
                ],
            )
            followup_text = [block.text for block in followup.content if hasattr(block, "text")]
            return "\n".join(followup_text) if followup_text else "\n".join(initial_text)

        except ImportError:
            raise ImportError("Anthropic library not installed. Run: pip install anthropic")
        except Exception as e:
            raise Exception(f"Claude API error: {str(e)}")

    def _claude_messages_create_with_retry(self, client, **kwargs):
        """Retry Anthropic calls on rate-limit errors using exponential backoff + jitter."""
        last_exc = None
        max_attempts = max(1, Config.CLAUDE_RATE_LIMIT_RETRIES)
        for attempt in range(1, max_attempts + 1):
            try:
                return client.messages.create(**kwargs)
            except Exception as exc:
                msg = str(exc).lower()
                is_rate_limited = (
                    "rate_limit_error" in msg or
                    "error code: 429" in msg or
                    "would exceed your organization's rate limit" in msg
                )
                if not is_rate_limited or attempt == max_attempts:
                    raise

                last_exc = exc
                sleep_s = (Config.CLAUDE_RATE_LIMIT_BASE_SLEEP_SEC * (2 ** (attempt - 1))) + random.uniform(0, 0.7)
                time.sleep(sleep_s)

        raise last_exc


# Global instance
llm_client = LLMClient()
